### ISSUE TITLE
ISE Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/icon-service#566]
Occurred on mainnet

```
2021-03-13 07:30:41,487 783 139965051762432 INFO regulator.py(114) IISS Regulate BH: 31718844 Covered by fee: 0 Covered by remain: 0 Corrected issue amount 3075118259590025435Regulator variable: Current calc period issued ICX: 38016724309111047851574 Prev calc period issued ICX: 132342850473422400858580 Remain over issued I-SCORE: -731
2021-03-13 07:30:41,488 783 139965051762432 INFO engine.py(84) ICX Issue icx. amount: 3075118259590025435 Total supply: 880299204205458544335591389 Treasury: 3345566070148711725148393
2021-03-13 07:30:41,488 783 139965051762432 INFO icon_service_engine.py(516) ISE TX_END: BH=31718844 txIndex=0 to=hx1000000000000000000000000000000000000000 method=NOT_CALL_DATA_TYPE duration=0.0008843950927257538
2021-03-13 07:30:41,514 783 139965051762432 INFO icon_service_engine.py(516) ISE TX_END: BH=31718844 txIndex=1 to=cx299d88908ab371d586c8dfe0ed42899a899e6e5b method=action duration=0.025901902001351118
2021-03-13 07:30:41,515 783 139965051762432 ERROR icon_service_engine.py(1521) ISE Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/iconservice/icon_service_engine.py", line 1271, in _handle_icx_send_transaction
    self._process_transaction(context, params, tx_result)
  File "/usr/local/lib/python3.7/site-packages/iconservice/icon_service_engine.py", line 1357, in _process_transaction
    tx_result.score_address = self._handle_score_invoke(context, to, params)
  File "/usr/local/lib/python3.7/site-packages/iconservice/icon_service_engine.py", line 1470, in _handle_score_invoke
    IconScoreEngine.invoke(context, to, data_type, data)
  File "/usr/local/lib/python3.7/site-packages/iconservice/iconscore/icon_score_engine.py", line 57, in invoke
    IconScoreEngine._call(context, icon_score_address, data)
  File "/usr/local/lib/python3.7/site-packages/iconservice/iconscore/icon_score_engine.py", line 118, in _call
    ret = score_func(func_name=func_name, kw_params=converted_params)
  File "/usr/local/lib/python3.7/site-packages/iconservice/iconscore/icon_score_base.py", line 454, in __call
    ret = score_func(*arg_params, **kw_params)
  File "/usr/local/lib/python3.7/site-packages/iconservice/iconscore/icon_score_base.py", line 320, in __wrapper
    res = func(calling_obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iconservice/iconscore/icon_score_base.py", line 286, in __wrapper
    res = func(calling_obj, *args, **kwargs)
  File "/data/mainnet/.score_data/score/01299d88908ab371d586c8dfe0ed42899a899e6e5b/0xb89051cbc02c2c46598636dcce73981170080420b47270bba041ac1543ac7671/main.py", line 623, in action
    self._process_cash_out(player_address, active_game_num)
  File "/data/mainnet/.score_data/score/01299d88908ab371d586c8dfe0ed42899a899e6e5b/0xb89051cbc02c2c46598636dcce73981170080420b47270bba041ac1543ac7671/main.py", line 373, in _process_cash_out
    game = json_loads(game_repository.get(player_address, active_game_num))
  File "/usr/local/lib/python3.7/site-packages/iconservice/iconscore/icon_score_base2.py", line 257, in json_loads
    return json.loads(src)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-03-13 07:30:41,519 783 139965051762432 ERROR icon_service_engine.py(1522) ISE Expecting value: line 1 column 1 (char 0)
```

**Comment by goldworm-icon** [comment]
Thank you for your report.
The above log means that json_loads() call is failed in a specific score.
This kind of error is very common.
If your node keeps building blocks well, you don't care about it.

**Comment by yakkle** [comment]
stale
